### ISSUE TITLE
Question: is it possible to avoid disposing manually?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [L4Digital/RxLoader#1]
The example code shows this:

    private void unsubscribe() {
        if (mDisposable != null && !mDisposable.isDisposed()) {
            mDisposable.dispose();
            mDisposable = null;
        }
    }

Is it possible to avoid calling this, and have the SDK handle unsubscribing automatically?

**Comment by randr0id** [comment]
There are other ways you can manage this, such as adding to a `CompositeDisposable` that can be cleared when appropriate. There is no automatic management of subscriptions.

**Comment by AndroidDeveloperLB** [comment]
Can you please show how to use CompositeDisposable in your sample?

**Comment by randr0id** [comment]
I don't think it makes sense in our sample code, but a quick example looks like:

```
    private CompositeDisposable cd = new CompositeDisposable();

    @Override
    protected void onDestroy() {
        cd.clear();
        super.onDestroy();
    }

    @Override
    public void onSubscribe(Disposable disposable) {
        cd.add(disposable);
    }
```

I would suggest researching managing disposables with RxJava to find better documentation and examples.

**Comment by AndroidDeveloperLB** [comment]
Isn't there a way to avoid this manual code? I mean, a major point of using Rx is to reduce code. This one makes you put more and more callbacks to handle...
Can you please make the most simple sample to show how to use this library, without the need to unsubscribe from it?

Also, how would you cancel a task this way, including interrupting the thread?
On AsyncTask, it's possible easily. On AsyncTaskLoader, it requires a bit more work (need access to the thread).
But here I can't see how you'd do it on this case.

**Comment by AndroidDeveloperLB** [comment]
For example, how would I replace this code with yours:

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        supportLoaderManager.initLoader(1, Bundle.EMPTY, object : LoaderCallbacks<Int> {
            override fun onCreateLoader(id: Int, args: Bundle): Loader<Int> {
                Log.d("AppLog", "onCreateLoader")
                return MyLoader(this@MainActivity)
            }

            override fun onLoadFinished(loader: Loader<Int>, data: Int?) {
                Log.d("AppLog", "done:" + data!!)
            }

            override fun onLoaderReset(loader: Loader<Int>) {}
        })
    }

    private class MyLoader(context: Context) : AsyncTaskLoader<Int>(context) {

        override fun onStartLoading() {
            super.onStartLoading()
            forceLoad()
        }

        override fun loadInBackground(): Int {
            Log.d("AppLog", "loadInBackground")
            try {
                Thread.sleep(10000)
            } catch (e: InterruptedException) {
                e.printStackTrace()
            }
            return 123
        }
    }
}
```

**Comment by randr0id** [comment]
> Can you please make the most simple sample to show how to use this library, without the need to unsubscribe from it?

This is not possible. Subscribing/Unsubscribing is always going to be the responsibility of the consumer. The provided example illustrates how to use RxLoader sufficiently.

**Comment by AndroidDeveloperLB** [comment]
Well, if it's an Activity, you can register to its lifecycle.
Not sure about Fragments though.

**Comment by AndroidDeveloperLB** [comment]
Here's one that might allow it in an easier way:
https://github.com/trello/RxLifecycle

**Comment by randr0id** [comment]
You should read this: http://blog.danlew.net/2017/08/02/why-not-rxlifecycle/

**Comment by AndroidDeveloperLB** [comment]
I see.
What about the normal Lifecycle, as Google presented?

Java:

    getLifecycle().addObserver(new LifecycleObserver() {
        @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
        void onDestroy() {
            ...
        }
    });

Kotlin:

    lifecycle.addObserver(object : LifecycleObserver {
        @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
        fun onDestroy() {
            ...
        }
    })

?

**Comment by randr0id** [comment]
That's probably fine, but how you manage subscriptions should be determined per case. If you want to auto manage them, take a look at the library suggested in that article: https://github.com/uber/AutoDispose

**Comment by AndroidDeveloperLB** [comment]
Have you used this repo?
Also, can you please answer the other question I asked here, of how to make the rxloader work with orientation change correctly?

**Comment by randr0id** [comment]
I have not used AutoDispose personally. I will take a look at your other open issue when I have some free time.

**Comment by AndroidDeveloperLB** [comment]
ok thanks.
